### ISSUE TITLE
FileNotFoundError on Windows 11

### ISSUE THREAD

**Issue by axv4444** [unconv/shortrocity#5]
@unconv Getting the following error, can anyone help?

C:\CodeRelated\shortrocity> python .\main.py .\source.txt
C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Generating script...
Generating narration...
Generating images...
Generating video...
```
C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\CodeRelated\shortrocity\main.py", line 91, in <module>
    video.create(narrations, basedir, output_file)
  File "C:\CodeRelated\shortrocity\video.py", line 56, in create
    duration = get_audio_duration(narration)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CodeRelated\shortrocity\video.py", line 10, in get_audio_duration
    return len(AudioSegment.from_file(audio_file))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\you\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Also I had to modify line 19 on main.py to:
`with open(sys.argv[1], errors='ignore') as f:`
So that it reached the place it reached now.

**Comment by axv4444** [comment]
Had to do `winget install ffmpeg` 
Then add it to the system path.
Just `pip install ffmpeg` doesn't work.
Thanks for the project.
