### ISSUE TITLE
cannot import name generate from elevenlabs

### ISSUE THREAD

**Issue by pannet1** [unconv/shortrocity#7]
`./main.py content_1.txt 
Traceback (most recent call last):
  File "/home/pannet1/Programs/py/youtube/shortrocity/./main.py", line 9, in <module>
    import narration
  File "/home/pannet1/Programs/py/youtube/shortrocity/narration.py", line 1, in <module>
    from elevenlabs import generate, set_api_key, save, RateLimitError
ImportError: cannot import name 'generate' from 'elevenlabs' `

has elevenlabs api changed

**Comment by unconv** [comment]
Yes, they've updated their library similarly as OpenAI but I haven't updated the code yet. You can use `elevenlabs==0.2.26` to make the current code work.
